backend:
  name: github
  repo: gxanshu/astro-decap-cms-starter #replace with your githu repo
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://astro-decapcms-starter.netlify.app/" # your site name

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: src/content/portfolio
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Photo Principale", name: "heroImage", widget: "image" }
      - { label: "Catégorie", name: "category", widget: "select", options: }
      - { label: "Description", name: "body", widget: "markdown" }

media_library:
  name: cloudinary
  config:
    cloud_name: dexmfv667
    api_key: kXR0nuyBkLGiiI94dT6Uw_O6XJA
    default_transformations:
      - [q_auto, f_auto] # Optimisation auto qualité/format
